en:
  languageName: English
  weight: 1

zh-hans:
  languageName: 简体中文
  weight: 2

zh-hant:
  languageName: 繁體中文
  weight: 3

de:
  languageName: Deutsch

fr:
  languageName: Français

ko:
  languageName: 한국어

ms:
  languageName: بهاس ملايو

nl:
  languageName: Nederlands

pt-br:
  languageName: Português

ru:
  languageName: Русский язык

vi:
  languageName: Tiếng Việt
