services:
  server:
    image: hugomods/hugo:exts-non-root
    volumes:
      - ./:/src
      - ~/.cache/hugo_cache:/tmp/hugo_cache
      - ~/Workspaces:/workspaces
    env_file:
      - .env
    command: server -p 7777
    ports:
      - 7777:7777
